'use client'

import { BarChart3, Bot, ChevronRight, Heart, Home, Moon, Settings, Sparkles, Sun, Target } from 'lucide-react'

type NavItem = { id: string; label: string; icon: typeof Home }
export const nav: NavItem[] = [{ id: 'today', label: 'Today', icon: Home }, { id: 'coach', label: 'AI Coach', icon: Bot }, { id: 'objectives', label: 'Objectives', icon: Target }, { id: 'progress', label: 'Progress', icon: BarChart3 }, { id: 'motivation', label: 'Motivation', icon: Sparkles }, { id: 'profile', label: 'Profile', icon: Heart }, { id: 'settings', label: 'Settings', icon: Settings }]

function Brand() { return <div className="flex items-center gap-3"><div className="flex size-10 items-center justify-center rounded-2xl bg-gradient-to-br from-violet-500 to-fuchsia-400 text-xl shadow-lg shadow-violet-200">🌱</div><div><p className="font-bold tracking-tight">LittleWins</p><p className="text-xs text-muted-foreground">a kinder way to grow</p></div></div> }
function NavButton({ item, active, onClick, mobile = false }: { item: NavItem; active: boolean; onClick: () => void; mobile?: boolean }) { const Icon = item.icon; return <button onClick={onClick} className={`flex items-center rounded-2xl text-sm font-medium transition-all ${mobile ? 'min-w-[62px] flex-col gap-1 px-2 py-2 text-[10px]' : 'w-full gap-3 px-3 py-3 text-left'} ${active ? 'bg-violet-100 text-violet-700 dark:bg-violet-950/60 dark:text-violet-200' : 'text-muted-foreground hover:bg-muted'}`}><Icon className={mobile ? 'size-5' : 'size-[18px]'} />{item.label}</button> }

export function Navigation({ page, setPage, dark, avatar, toggleTheme }: { page: string; setPage: (page: string) => void; dark: boolean; avatar: string; toggleTheme: () => void }) { return <><aside className="fixed inset-y-0 left-0 z-30 hidden w-64 flex-col border-r border-border/60 bg-background/75 px-5 py-7 backdrop-blur-xl lg:flex"><Brand /><div className="mt-12 flex flex-col gap-2">{nav.map(item => <NavButton key={item.id} item={item} active={page === item.id} onClick={() => setPage(item.id)} />)}</div><div className="mt-auto rounded-3xl bg-gradient-to-br from-violet-100 to-amber-50 p-5 dark:from-violet-950/50 dark:to-amber-950/30"><Sparkles className="mb-3 text-violet-500" /><p className="text-sm font-medium leading-relaxed">Small steps every day create remarkable results.</p><button onClick={() => setPage('motivation')} className="mt-4 text-xs font-bold text-violet-600">Find your spark<ChevronRight className="ml-1 inline size-3" /></button></div></aside><header className="sticky top-0 z-20 flex items-center justify-between border-b border-border/50 bg-[#fbfaf8]/80 px-5 py-4 backdrop-blur-xl dark:bg-[#151617]/80 lg:px-12"><div className="flex items-center gap-3 lg:hidden"><div className="flex size-9 items-center justify-center rounded-xl bg-violet-500 text-lg">🌱</div><span className="font-bold">LittleWins</span></div><div className="hidden lg:block"><p className="text-sm text-muted-foreground">{new Date().toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric' })}</p></div><div className="flex items-center gap-2"><button onClick={toggleTheme} className="rounded-full p-2 text-muted-foreground hover:bg-muted">{dark ? <Sun /> : <Moon />}</button><button onClick={() => setPage('profile')} className="flex size-9 items-center justify-center rounded-full bg-violet-100 text-lg text-violet-700 dark:bg-violet-950 dark:text-violet-200">{avatar}</button></div></header><nav className="fixed inset-x-0 bottom-0 z-30 flex justify-around overflow-x-auto border-t border-border/50 bg-background/90 px-1 py-2 backdrop-blur-xl lg:hidden">{nav.map(item => <NavButton key={item.id} item={item} active={page === item.id} onClick={() => setPage(item.id)} mobile />)}</nav></> }
